version: '3'

services:
  frontend:
    container_name: frontend-vue
    image: node:latest
    volumes:
      - ./Vue:/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "cd /app && npm run build && npm run pro"
    networks:
      - todo-list-network
  app:
    container_name: backend-kotlin
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    networks:
      - todo-list-network
  db:
    container_name: backend-database
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TaskDatabase
    networks:
      - todo-list-network
networks:
  todo-list-network: