version: '3'

services:
  testdb:
    container_name: backend-database-testing
    image: postgres:14-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TaskDatabase
