version: '3.8'

services:
  app:
    container_name: backend-app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
