version: '3'
services:
  frontend:
    image: node:latest
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "cd /app && npm install && npm run serve"
